--- #YAML:1.0
name: Exception-System
abstract: Exception class for system or library calls
version: 0.06
author:
  - Piotr Roszatycki <dexter@debian.org>
license: perl
distribution_type: module
requires:
  perl: 5.006
  Exception::Base: 0.03
urls:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Piotr Roszatycki <dexter@debian.org>
